# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "feature/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: systemutviklerskolen-todo-app-backend
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: systemutviklerskolen-todo-app-backend
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: systemutviklerskolen-todo-app-backend

    - name: Use node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: NPM install
      run: npm install
      working-directory: systemutviklerskolen-todo-app-frontend

    - name: npm build frontend
      run: npm run build
      working-directory: systemutviklerskolen-todo-app-frontend

    - name: dotnet publish
      run: dotnet publish -c release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Copy frontend to artifact
      run: cp -r systemutviklerskolen-todo-app-frontend/build ./myapp/todo-app-frontend

    - name: upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

    - name: Deploy application to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.DOTNET-ROOT}}/myapp
        

      
